services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - posts_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

  redis:
    image: redis:latest
    ports:
      - $REDIS_PORT:$REDIS_PORT
    env_file:
      - ../../.env

  web:
    build:
      context: ../..
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - DOCKER_BUILDKIT=1
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ../../.env

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - ../../.env
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT

  flower:
    image: mher/flower
    ports:
      - ${FLOWER_PORT:-5555}:${FLOWER_PORT:?error}
    depends_on:
      - rabbitmq
    env_file:
      - ../../.env

  celery_worker:
    build:
      context: ../..
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - DOCKER_BUILDKIT=1
    command: bash -c "celery -A app.celery_tasks.celery_app worker -B --loglevel=info"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - web
    volumes:
      - ../../admin:/app/admin
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  posts_data:
