services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - posts_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  redis:
    image: redis:latest
    env_file:
      - ../.env

  web:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - DOCKER_BUILDKIT=1
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - ../.env

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - ../.env

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  celery_worker:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - DOCKER_BUILDKIT=1
    command: bash -c "celery -A app.celery_tasks.celery_app worker -B --loglevel=info"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - web
    env_file:
      - ../.env

volumes:
  posts_data:
